# Generated by Django 5.1.2 on 2024-11-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_follow_userprofiles_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
