# Generated by Django 5.1.2 on 2024-11-05 02:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_create_at_follow_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='UserProfiles',
            name='bio',
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=500, verbose_name='Biografia'),
        ),
    ]
