# Generated by Django 5.1.2 on 2024-11-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofiles_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='followers',
            field=models.ManyToManyField(related_name='Following', through='profiles.Follow', to='profiles.userprofiles'),
        ),
    ]
